### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by SatireY** [peract/peract#38]
When I follow the quick start tutorial to run python dataset_generator.py --tasks=open_drawer \
--save_path=$PERACT_ROOT/data/val \
--image_size=128,128 \
--renderer=opengl \
--episodes_per_task=10 \
--processes=1 \
--all_variations=True 
errors occur:
```/ home/hychen/anaconda3 / envs/peract/lib/python3.8 / site - packages/torchvision/transforms/transforms. The py: 329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
warnings.warn(
loaded weights from /home/hychen/project/peract/ckpts/multi/PERACT_BC/seed0/weights/600000/QAttentionAgent_layer0.pt
/home/hychen/project/YARR/yarr/utils/rollout_generator.py:31: UserWarning:  Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single  numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at .. /torch/csrc/utils/tensor_new.cpp:230.)
prepped_data = {k:torch.tensor([v], device=self._env_device) for k, v in obs_history.items()}
[CoppeliaSim:loadinfo]   done.
Process Process-2:
Traceback (most recent call last):
The File "/ home/hychen/anaconda3 / envs/peract/lib/python3.8 / multiprocessing/process. Py", line 315, in _bootstrap
self.run()
The File "/ home/hychen/anaconda3 / envs/peract/lib/python3.8 / multiprocessing/process. Py", line 108, in the run
self._target(*self._args, **self._kwargs)
File "/home/hychen/project/YARR/yarr/runners/independent_env_runner.py", line 119, in start
self._internal_env_runner._run_eval_independent('eval_env',
File "/home/hychen/project/YARR/yarr/runners/_independent_env_runner.py", line 228, in _run_eval_independent
raise e
File "/home/hychen/project/YARR/yarr/runners/_independent_env_runner.py", line 221, in _run_eval_independent
for s in self._agent.act_summaries():
File "/home/hychen/project/peract/helpers/preprocess_agent.py", line 84, in act_summaries
return self._pose_agent.act_summaries()
File "/home/hychen/project/peract/agents/peract_bc/qattention_stack_agent.py", line 104, in act_summaries
s.extend(qa.act_summaries())
File "/home/hychen/project/peract/agents/peract_bc/qattention_peract_bc_agent.py", line 646, in act_summaries
transforms.ToTensor()(visualise_voxel(
File "/home/hychen/project/peract/helpers/utils.py", line 234, in visualise_voxel
r = offscreen_renderer or pyrender.OffscreenRenderer(
The File "/ home/hychen/anaconda3 / envs/peract/lib/python3.8 / site - packages/pyrender offscreen. Py", line 31, in __init__
self._create()
The File "/ home/hychen/anaconda3 / envs/peract/lib/python3.8 / site - packages/pyrender offscreen. Py", line 149, in _create
self._platform.init_context()
The File "/ home/hychen anaconda3 / envs/peract/lib/python3.8 / site - packages/pyrender/platforms/pyglet_platform py", line 62, in init_context
'internal error message was "{}"'.format(e)
UnboundLocalError: local variable 'e' referenced before assignment
```
Need your help

**Comment by MohitShridhar** [comment]
@SatireY, not sure what's happening here. Maybe downgrade/upgrade pyrender?
