### ISSUE TITLE
problem with size mismatch

### ISSUE THREAD

**Issue by lurenjia384** [peract/peract#42]
Process Process-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/peract/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/peract/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/somebody/peract/YARR/yarr/runners/independent_env_runner.py", line 119, in start
    self._internal_env_runner._run_eval_independent('eval_env',
  File "/home/somebody/peract/YARR/yarr/runners/_independent_env_runner.py", line 168, in _run_eval_independent
    self._agent.load_weights(weight_path)
  File "/home/somebody/peract/peract/helpers/preprocess_agent.py", line 87, in load_weights
    self._pose_agent.load_weights(savedir)
  File "/home/somebody/peract/peract/agents/peract_bc/qattention_stack_agent.py", line 109, in load_weights
    qa.load_weights(savedir)
  File "/home/somebody/peract/peract/agents/peract_bc/qattention_peract_bc_agent.py", line 667, in load_weights
    self._q.load_state_dict(state_dict, strict=False)
  File "/root/anaconda3/envs/peract/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for QFunction:
	size mismatch for _voxelizer._ones_max_coords: copying a param with shape torch.Size([3, 65536, 1]) from checkpoint, the shape in current model is torch.Size([1, 65536, 1]).
	size mismatch for _voxelizer._flat_output: copying a param with shape torch.Size([22285368]) from checkpoint, the shape in current model is torch.Size([7428456]).
	size mismatch for _voxelizer._tiled_batch_indices: copying a param with shape torch.Size([3, 65536, 1]) from checkpoint, the shape in current model is torch.Size([1, 65536, 1]).
	size mismatch for _voxelizer._index_grid: copying a param with shape torch.Size([3, 102, 102, 102, 3]) from checkpoint, the shape in current model is torch.Size([1, 102, 102, 102, 3]).
QMutex: destroying locked mutex

**Comment by MohitShridhar** [comment]
@lurenjia384, this looks like something is going wrong with how the checkpoints are saved during training. 

Could this be related: https://github.com/peract/peract/issues/24 ?
