### ISSUE TITLE
Error when running python setup.py develop: .* suffix can only be used with `==` or `!=` operators     PyYAML (>=5.1.*)

### ISSUE THREAD

**Issue by astonastonaston** [peract/peract#49]
I installed PyRep, Coppelia, and the requirement packages for peract already, and was trying to setup peract by running ``python setup.py develop``. But I get the following error:

```
(peract_env) nan@nan-Alienware-m15:~/Desktop/peract$ python setup.py develop
running develop
/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing peract.egg-info/PKG-INFO
writing dependency_links to peract.egg-info/dependency_links.txt
writing requirements to peract.egg-info/requires.txt
writing top-level names to peract.egg-info/top_level.txt
reading manifest file 'peract.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'peract.egg-info/SOURCES.txt'
running build_ext
Creating /home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/peract.egg-link (link to .)
peract 0.1.0 is already the active version in easy-install.pth

Installed /home/nan/Desktop/peract
Processing dependencies for peract==0.1.0
Traceback (most recent call last):
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3070, in _dep_map
    return self.__dep_map
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2863, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 216, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 231, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    setup(
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/command/develop.py", line 126, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 785, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2786, in requires
    dm = self._dep_map
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3072, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3082, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "/home/nan/.virtualenvs/peract_env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

```

I also got this warning after installing the requirements for peract:

```
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

Anyone knows what's wrong? It seems the omegaconf==2.0.6 package is broken according to a similar issue here:

[https://github.com/python-poetry/poetry/issues/4206](url)

**Comment by astonastonaston** [comment]
I saw this dependency problem on omegaconf is caused by hydra-core==1.0.5 in peract's requirements.txt. I changed that to hydra-core==1.1.0 and installed again, and it runs without error. I don't know if this can make future training or evaluation fail though.
